"""Shared visual language for the static research pages."""

SHARED_CSS = r"""
:root{--ui-bg:#080B12;--ui-panel:#0F1420;--ui-panel-2:#161D2C;--ui-border:#293346;--ui-border-strong:#37435C;--ui-ink:#DADFE8;--ui-ink-2:#98A0B4;--ui-ink-3:#636B80;--ui-up:#E6432F;--ui-down:#37B25C;--ui-accent:#F0BB55;--ui-radius:6px}
.ui-page-summary{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0 18px}.ui-summary-item{min-width:124px;padding:9px 12px;background:var(--ui-panel);border:1px solid var(--ui-border);border-radius:var(--ui-radius)}.ui-summary-label{display:block;color:var(--ui-ink-3);font-size:.64rem;letter-spacing:.06em;text-transform:uppercase}.ui-summary-value{display:block;margin-top:2px;color:var(--ui-ink);font-size:1rem;font-weight:750;font-variant-numeric:tabular-nums}.ui-summary-note{display:block;color:var(--ui-ink-2);font-size:.68rem}
.ui-event-badge{display:inline-flex;align-items:center;gap:4px;padding:2px 7px;border:1px solid var(--ui-border-strong);border-radius:5px;color:var(--ui-ink-2);font-size:.68rem;font-weight:700;white-space:nowrap}.ui-event-badge[data-direction="up"]{color:var(--ui-up);border-color:rgba(230,67,47,.48);background:rgba(230,67,47,.10)}.ui-event-badge[data-direction="down"]{color:var(--ui-down);border-color:rgba(55,178,92,.48);background:rgba(55,178,92,.10)}.ui-event-badge[data-confidence="draft"]{border-style:dashed;color:var(--ui-ink-3);background:transparent}
.ui-empty{padding:16px 12px;border:1px dashed var(--ui-border-strong);border-radius:var(--ui-radius);color:var(--ui-ink-2);font-size:.76rem;text-align:center}.ui-empty strong{display:block;color:var(--ui-ink);margin-bottom:3px}.ui-card-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:10px}.ui-compact-card{display:grid;gap:5px;min-width:0;padding:11px 12px;background:var(--ui-panel);border:1px solid var(--ui-border);border-radius:var(--ui-radius);transition:border-color .15s,background .15s,transform .15s}.ui-compact-card:hover{border-color:var(--ui-border-strong);background:var(--ui-panel-2);transform:translateY(-1px)}.ui-card-head{display:flex;align-items:baseline;gap:7px;min-width:0}.ui-card-name{overflow:hidden;color:var(--ui-ink);font-size:.86rem;font-weight:750;text-overflow:ellipsis;white-space:nowrap}.ui-card-id{color:var(--ui-ink-3);font-size:.68rem;font-variant-numeric:tabular-nums}.ui-card-meta{overflow:hidden;color:var(--ui-ink-2);font-size:.7rem;text-overflow:ellipsis;white-space:nowrap}.ui-card-stats{display:flex;flex-wrap:wrap;align-items:center;gap:5px 9px;color:var(--ui-ink-2);font-size:.72rem;font-variant-numeric:tabular-nums}.ui-card-detail{margin-top:3px;padding-top:7px;border-top:1px solid var(--ui-border);color:var(--ui-ink-2);font-size:.72rem}
@media(max-width:640px){.ui-summary-item{flex:1 1 100px;min-width:0}.ui-card-grid{grid-template-columns:1fr}.ui-compact-card{padding:9px 10px}.ui-compact-card:hover{transform:none}}@media(prefers-reduced-motion:reduce){.ui-compact-card{transition:none}.ui-compact-card:hover{transform:none}}
"""
